apiVersion: apps/v1
kind: Deployment
metadata:
  name: performance
  labels:
    app: performance
spec:
  replicas: 3
  selector:
    matchLabels:
      app: performance
  template:
    metadata:
      labels:
        app: performance
    spec:
      containers:
      - name: my-app-container
        image: myacr6bea8344.azurecr.io/performance:latest  # Replace with your Docker image URL
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"  # Example environment variable; adjust as needed
---
apiVersion: v1
kind: Service
metadata:
  name: performance
  labels:
    app:performance
spec:
  type: LoadBalancer  # Adjust this if you want a different service type
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: performance
