apiVersion: apps/v1
kind: Deployment
metadata:
  name: performance
  labels:
    app: performance
    env: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: performance
  template:
    metadata:
      labels:
        app: performance
    spec:
      containers:
      - name: performance-container
        image: myacr6bea8344.azurecr.io/performance:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: performance
  labels:
    app: performance
spec:
  type: LoadBalancer  # Adjust this if you want a different service type (e.g., ClusterIP or NodePort)
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP  # This field is optional, default is TCP
  selector:
    app: performance
